spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        secure: true

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

app:
  security:
    allowed-origins:
      - ${ADMIN_FRONTEND_ORIGIN}
  bootstrap-admin:
    enabled: ${BOOTSTRAP_ADMIN_ENABLED:false}
